# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "draw-menu"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
parameter_overrides = [
    "stage=home",
    "githubUser=kevin6100918-git",
    "githubAccessToken=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",
    "githubRepoName=drawMenu",
    "lineBotChannelAccessToken=SIxYzwqbUtMwICkUzoGagLwEtCXjKHmWkg9dcG4rJBkKIS6A4RSQpdPVISLnVd5skPCDhu1AC3Na+aqD+IvuREGVWA2TTgD5UdzLi5pQ+PlAky00fc03J3jFkjTVpDnqQCr1ibPtR/8Nl4VtPeXzlwdB04t89/1O/w1cDnyilFU=",
    "lineBotChannelSecret=bb01a622bd926a3339c8883b994763cf",
    "lineBotChannelID=2000268212",
]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
